apiVersion: apps/v1
kind: Deployment
metadata:
  name: React-app
spec:
  selector:
    matchLabels:
      app: React-app
  template:
    metadata:
      labels:
        app: React-app
    spec:
      containers:
      - name: React-app
        image: bopgeek/gitops01:f04288594db8cf639c29a1ae6b8a14cca24165b2
        ports:
        - containerPort: 3000
