apiVersion: apps/v1
kind: Deployment
metadata:
  name: React-app
spec:
  selector:
    matchLabels:
      app: React-app
  template:
    metadata:
      labels:
        app: React-app
    spec:
      containers:
      - name: React-app
        image: bopgeek/gitops01:5b7496d8bbdf635001c693c0a7952909584a3377
        ports:
        - containerPort: 3000
