apiVersion: apps/v1
kind: Deployment
metadata:
  name: React-app
spec:
  selector:
    matchLabels:
      app: React-app
  template:
    metadata:
      labels:
        app: React-app
    spec:
      containers:
      - name: React-app
        image: bopgeek/gitops01:fd0b61b0e78843c05c6fc10b0b8937721e68f831
        ports:
        - containerPort: 3000
